

pl_trainer_func:
  max_epochs: 250
  accelerator: 'gpu'
  devices: 1
  precision: 32 # 精度
  # logger: logger # 日志管理器
  val_check_interval: 0.5

model:
  name: 'ResNet34'
  model_arg: 
    input_channel: 3
    n_outputs: 10

  trainer: # 设置训练模型相关的参数，如优化器、学习率等
    epoch: ${pl_trainer_func.max_epochs}
    device: ${pl_trainer_func.devices} # devices > 1时自定义的trainer中用来对logger操作用
    name: 'ResNetTrainer'

    trainer_arg:
      optimizer: # 定义第一个优化器的参数
        name: 'SGD'
        optimizer_arg:
          lr: 0.01
          momentum: 0.9
          weight_decay: 5E-4

      lr_scheduler:
        name: 'MultiStepLR'
        scheduler_arg:
          milestones: 
            - ${int(trainer.epoch * 0.25)}
            - ${int(trainer.epoch * 0.5)}
            - ${int(trainer.epoch * 0.75)}
          gamma: 0.5


# 定义训练集相关参数
train_dataset:
  name: CIFAR10

  dataset_arg:
    root: './data'
    download: true
    train: true
    noise_type: 'pairflip'
    noise_rate: 0.2

  dataloader_arg:
    batch_size: 128
    num_workers: 4
    shuffle: true
    # pin_memory: true

  transform:
    RandomCrop:
        size: 4
        padding: 4
    RandomHorizontalFlip: null
    ToTensor: null

# 定义测试集相关参数
test_dataset:
  name: CIFAR10

  dataset_arg:
    root: './data'
    download: true
    train: false
    noise_type: 'pairflip'
    noise_rate: 0.2

  dataloader_arg:
    batch_size: 128
    num_workers: 4
    shuffle: false
    # pin_memory: true

  transform:
    ToTensor: null
  
